blank_issues_enabled: false
contact_links:
  - name: ğŸ‘¨â€ğŸ« Nano Banana Pro éŒ¦å›Šå¦™è¨ˆï¼šè³‡è¨Šåœ–è¡¨ç”Ÿæˆçš„å·¥ç¨‹åŒ–æ–¹æ³•
    url: https://learn.duotify.com/courses/nbp-1
    about: è«‹åˆ°èª²ç¨‹å®˜ç¶²æŸ¥é–±æœ¬èª²ç¨‹æœ€æ–°è³‡è¨Š
  - name: ğŸ’¬ Discord (å­¸å“¡é™å®š)
    url: https://discord.com/channels/1263171994468487179/1451838735820787756
    about: æœ‰å•é¡Œæˆ–å»ºè­°ï¼Ÿæ­¡è¿åˆ° Discord äº¤æµï¼
  - name: ğŸ“– Espanso å®˜æ–¹æ–‡ä»¶
    url: https://espanso.org/docs/
    about: äº†è§£æ›´å¤šé—œæ–¼ Espanso çš„ä½¿ç”¨æ–¹å¼
